#!/usr/bin/env python3
"""Regression checks for creative brief, candidate, and Critic boundaries."""

from __future__ import annotations

import argparse
import copy
import csv
import io
import json
import os
import subprocess
import sys
import threading
import tempfile
import time
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

import adco_core.creative_contract as creative_contract_module

from ad_creative_operator import (
    adversarial_council_evidence,
    creative_proposal_scan_files,
    command_creative_review,
    default_adversarial_targets,
    ensure_delivery_project,
    ensure_project,
    now_iso,
    render_creative_proposal,
    render_thread_execution_plan,
    review_creative_quality,
    review_film_quality,
    write_text,
)
from adco_core.creative_contract import (
    BRIEF_CONTRACT_REL,
    BRIEF_MANIFEST_REL,
    BRIEF_SNAPSHOT_REL,
    CANDIDATE_SCHEMA_REL,
    CLAIM_BEARING_FIELDS,
    CREATIVE_DIRECTION_FIELDS,
    CREATIVE_ROOT,
    CURRENT_GENERATION_REL,
    DETERMINISTIC_LINT_RECEIPT_REL,
    _current_snapshot,
    _prohibited_claims,
    audit_local_operator_assertions,
    confirm_creative_requirement,
    create_creative_brief,
    current_creative_generation_paths,
    file_sha256,
    import_creative_candidate,
    payload_sha256,
    record_local_operator_assertion,
    resolve_creative_constraint,
    revoke_local_operator_assertion,
    review_creative_candidate,
)
from adco_core.facts import run_evidence_intake as _run_evidence_intake_impl
from adco_core.ingestion import EVIDENCE_REL
from adco_core.safe_write import atomic_write_bytes as real_atomic_write_bytes
from adco_core.safe_write import (
    atomic_write_text,
    project_advisory_lock,
    read_optional_project_bytes as real_read_optional_project_bytes,
    read_project_bytes,
)


def run_evidence_intake(
    project: Path,
    source_rows: list[dict[str, str]],
    *,
    max_total_chars: int = 2_000_000,
):
    """Register fixture sources before exercising the real intake path."""
    source_path = project / "AD-creative/orchestrator/source_events.csv"
    with source_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fields = list(reader.fieldnames or [])
        existing = [dict(row) for row in reader]
    existing_ids = {row.get("source_event_id") for row in existing}
    for source in source_rows:
        source_id = source["source_event_id"]
        if source_id in existing_ids:
            continue
        existing.append(
            {
                "source_event_id": source_id,
                "received_at": "2026-07-22T00:00:00+08:00",
                "source_owner": "fixture-human",
                "source_type": "file",
                "declared_semantics": source.get("declared_semantics", "test fixture"),
                "file_paths": source["file_paths"],
                "raw_summary": "registered test fixture",
                "trust_level": "human_reviewed",
                "affects_requirements": "yes",
                "affects_artifacts": "",
                "supersedes_event_ids": "",
                "notes": "test-only registration",
            }
        )
        existing_ids.add(source_id)
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(existing)
    return _run_evidence_intake_impl(
        project,
        source_rows,
        max_total_chars=max_total_chars,
    )


def _append_confirmation_event(
    project: Path,
    *,
    event_id: str,
    semantics: str,
    affects_requirements: set[str],
    affects_artifacts: set[str] | None = None,
) -> str:
    del event_id  # IDs are generated by the public capture path.
    return record_local_operator_assertion(
        project,
        semantics=semantics,
        requirement_ids=affects_requirements,
        artifact_bindings=affects_artifacts or set(),
        note="test-only local workflow assertion",
    ).assertion_ref


def _prepare(project: Path) -> tuple[str, str]:
    ensure_project(project)
    source = project / "brief.md"
    source.write_text(
        "客户已提供产品图和品牌 logo。客户要求面向雨天通勤人群制作可编辑广告提案。",
        encoding="utf-8",
    )
    result = run_evidence_intake(
        project,
        [
            {
                "source_event_id": "SRC-001",
                "file_paths": source.name,
                "declared_semantics": "creative fixture",
            }
        ],
    )
    brief = create_creative_brief(project)
    return brief.snapshot_sha256, result.ingestion.chunks[0].chunk_id


def _confirm_requirements(project: Path) -> None:
    path = project / "AD-creative/orchestrator/requirements.csv"
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = [dict(row) for row in reader]
    for index, row in enumerate(rows, start=1):
        confirmation_ref = _append_confirmation_event(
            project,
            event_id=f"CONFIRM-REQ-{index:03d}",
            semantics="creative_requirement_confirmation",
            affects_requirements={row["requirement_id"]},
        )
        confirm_creative_requirement(
            project,
            row["requirement_id"],
            confirmation_ref=confirmation_ref,
        )


def _prepare_hard_constraints(
    project: Path, *, confirm: bool = True
) -> tuple[str, str]:
    ensure_project(project)
    source = project / "hard-constraint-brief.md"
    source.write_text(
        "\n".join(
            [
                "视频时长必须控制在20秒以内。",
                "最多2位演员。",
                "拍摄只能在公寓客厅和便利店门口。",
                "必须有真实产品露出。",
                "不得使用睡眠、醒酒、减肥、健康或医疗宣称。",
            ]
        ),
        encoding="utf-8",
    )
    result = run_evidence_intake(
        project,
        [
            {
                "source_event_id": "SRC-HARD-001",
                "file_paths": source.name,
                "declared_semantics": "hard-constraint fixture",
            }
        ],
    )
    if confirm:
        _confirm_requirements(project)
    brief = create_creative_brief(project)
    return brief.snapshot_sha256, result.ingestion.chunks[0].chunk_id


def _direction(number: int, evidence_ref: str) -> dict[str, object]:
    values: dict[str, object] = {
        "direction_id": f"DIR-{number:02d}",
        "name": "雨线显形" if number == 1 else "收纳时刻",
        "human_tension": "通勤者不相信泛泛的防水承诺，只相信眼前可见的具体变化。",
        "brand_truth": "品牌的三层防水结构和可收纳设计均由已绑定资料支持。",
        "audience_truth": "城市通勤人群会在出门前快速判断装备是否值得携带。",
        "single_minded_proposition": "让防护价值在真实动作中被看见。",
        "creative_mechanism": "雨滴路径实时显形" if number == 1 else "一镜到底折叠收纳",
        "key_visual": "雨水沿夹克表面形成清晰分流线并在胸前定格。" if number == 1 else "夹克从穿着状态连续折叠进入通勤包侧袋。",
        "story_or_behavior": "镜头跟随通勤者穿过雨幕，防护效果通过连续动作而非旁白完成证明。" if number == 1 else "镜头从办公室门口跟随人物收纳夹克并切换到周末步道使用。",
        "product_role": "产品是完成防护或收纳动作的因果核心，不是背景道具。",
        "channel_execution": "15 秒竖屏视频与一张动作中段关键视觉。",
        "why_brand_can_own_it": "该机制直接依赖资料中已确认的三层面料与可收纳结构，替换普通品牌后因果链会失效。",
        "production_risk": "需要可控降雨、连续动作排练和面料反光测试。",
        "evidence_refs": [evidence_ref],
        "runtime_seconds": 15,
        "cast_count": 1,
        "locations": ["办公室门口", "周末步道"],
        "product_exposure": {
            "physical_product_visible": True,
            "description": "真实夹克持续出镜并展示防水或收纳动作。",
        },
        "claims": [],
    }
    assert set(values) == set(CREATIVE_DIRECTION_FIELDS)
    return values


def _hard_constraint_direction(number: int, evidence_ref: str) -> dict[str, object]:
    values = _direction(number, evidence_ref)
    values.update(
        {
            "key_visual": "便利店门口出现真实产品罐身特写，包装在画面中央清晰可见。",
            "story_or_behavior": "两位演员在便利店门口拿起真实产品，随后回到公寓客厅开罐饮用。",
            "channel_execution": "抖音和小红书使用18秒竖屏视频，保留产品特写。",
            "production_risk": "两位演员、两个许可场景和真实产品均需在拍摄前确认。",
            "runtime_seconds": 18,
            "cast_count": 2,
            "locations": ["便利店门口", "公寓客厅"],
            "product_exposure": {
                "physical_product_visible": True,
                "description": "真实产品罐身在画面中央特写，演员拿起并开罐饮用。",
            },
            "claims": [],
        }
    )
    return values


def _assert_import_rejected_without_persistence(
    project: Path, candidate_path: Path, expected_error: str
) -> None:
    protected = [project / CURRENT_GENERATION_REL]
    before = {
        path: path.read_bytes() if path.is_file() else None
        for path in protected
    }
    generations_before = sorted(
        path.name
        for path in (project / CREATIVE_ROOT / "generations").glob("gen-*")
    )
    try:
        import_creative_candidate(project, candidate_path)
    except ValueError as exc:
        assert expected_error in str(exc), str(exc)
    else:
        raise AssertionError(f"creative import must fail: {expected_error}")
    after = {
        path: path.read_bytes() if path.is_file() else None
        for path in protected
    }
    generations_after = sorted(
        path.name
        for path in (project / CREATIVE_ROOT / "generations").glob("gen-*")
    )
    assert after == before
    assert generations_after == generations_before


def test_brief_generates_contracts_not_directions() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-brief-") as raw:
        project = Path(raw)
        snapshot_sha, _ = _prepare(project)
        assert (project / BRIEF_SNAPSHOT_REL).is_file()
        assert (project / BRIEF_CONTRACT_REL).is_file()
        assert (project / CANDIDATE_SCHEMA_REL).is_file()
        assert not (project / CURRENT_GENERATION_REL).exists()
        payload = render_creative_proposal(project)
        assert payload["directions_generated"] == 0
        assert payload["deprecated_alias"] == "creative-brief"
        assert "ART-AUTO-CREATIVE-DIRECTIONS" not in payload["artifact_ids"]
        snapshot = json.loads((project / BRIEF_SNAPSHOT_REL).read_text(encoding="utf-8"))
        assert snapshot["brief_snapshot_sha256"] == snapshot_sha


def test_candidate_requires_evidence_and_distinct_mechanisms() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-candidate-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref), _direction(2, evidence_ref)],
        }
        candidate_path = project / "candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        imported = import_creative_candidate(project, candidate_path)
        assert imported.direction_count == 2
        review = review_creative_candidate(project, independent_critic_required=True)
        assert review.status == "PARTIAL_PASS"
        assert review.receipt["independent_critic_required"] is True
        assert review.receipt["creative_quality"] == "NOT_APPROVED_BY_DETERMINISTIC_LINT"
        for direction_id in ["DIR-01", "DIR-02"]:
            assert review.receipt["evidence_traceability"][direction_id]["status"] == (
                "PROVENANCE_ONLY"
            )
            assert "semantic claim support is not verified" in review.receipt[
                "evidence_traceability"
            ][direction_id]["reason"]
            assert review.receipt["brief_adherence"][direction_id]["status"] == (
                "NOT_APPLICABLE"
            )
        for field in [
            "brief_adherence",
            "insight_quality",
            "brand_ownership",
            "mechanism_difference",
            "key_visual_clarity",
            "shootability",
            "production_risk",
            "brand_replacement_test",
            "verdict",
        ]:
            assert field in review.receipt

        review.receipt_path.unlink()
        content_review = review_creative_candidate(
            project,
            independent_critic_required=False,
        )
        assert content_review.status == "PARTIAL_PASS"
        assert content_review.receipt_path is None
        assert not review.receipt_path.exists()
        assert content_review.receipt["independent_critic_required"] is False
        assert content_review.receipt["verdict"] == (
            "STRUCTURE_PASS_HUMAN_JUDGMENT_REQUIRED"
        )

        duplicate = copy.deepcopy(candidate)
        duplicate["directions"][1]["creative_mechanism"] = duplicate["directions"][0][
            "creative_mechanism"
        ]
        duplicate_path = project / "duplicate.json"
        duplicate_path.write_text(json.dumps(duplicate, ensure_ascii=False), encoding="utf-8")
        try:
            import_creative_candidate(project, duplicate_path)
        except ValueError as exc:
            assert "duplicate creative mechanism" in str(exc)
        else:
            raise AssertionError("duplicate creative mechanisms must fail")

        unbound = copy.deepcopy(candidate)
        unbound["directions"][0]["evidence_refs"] = ["EVC-NOT-REAL"]
        unbound_path = project / "unbound.json"
        unbound_path.write_text(json.dumps(unbound, ensure_ascii=False), encoding="utf-8")
        try:
            import_creative_candidate(project, unbound_path)
        except ValueError as exc:
            assert "evidence_refs" in str(exc)
        else:
            raise AssertionError("unbound creative evidence must fail")


def test_hard_constraints_are_semantically_checked_and_fail_closed() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-hard-constraints-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare_hard_constraints(project)
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        assert contract["contract_version"] == "1.1"
        assert {item["kind"] for item in contract["hard_constraints"]} == {
            "runtime_max_seconds",
            "cast_max",
            "location_allowlist",
            "product_exposure_required",
            "prohibited_claims",
        }
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [
                _hard_constraint_direction(1, evidence_ref),
                _hard_constraint_direction(2, evidence_ref),
            ],
        }
        candidate_path = project / "hard-constraint-candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        import_creative_candidate(project, candidate_path)
        review = review_creative_candidate(project)
        assert review.status == "PARTIAL_PASS", review.receipt
        assert not review.blocking_issues
        for direction_id in ["DIR-01", "DIR-02"]:
            assert review.receipt["brief_adherence"][direction_id]["status"] == "PASS"
            checks = review.receipt["brief_constraint_checks"][direction_id]
            assert {item["status"] for item in checks.values()} == {"PASS"}

        timeline = copy.deepcopy(candidate)
        timeline["directions"][0]["story_or_behavior"] = (
            "前2秒，两位演员在便利店门口拿起真实产品；随后一人特写，"
            "再回到公寓客厅完成聊天和开罐动作。"
        )
        timeline["directions"][0]["channel_execution"] = (
            "总时长为18秒的竖屏视频；0–2s 建立关系，3秒特写产品。"
        )
        timeline_path = project / "timeline-and-single-shot.json"
        timeline_path.write_text(
            json.dumps(timeline, ensure_ascii=False), encoding="utf-8"
        )
        import_creative_candidate(project, timeline_path)
        timeline_review = review_creative_candidate(project)
        assert timeline_review.receipt["brief_adherence"]["DIR-01"]["status"] == (
            "PASS"
        ), timeline_review.receipt

        explicit_runtime_conflict = copy.deepcopy(candidate)
        explicit_runtime_conflict["directions"][0]["channel_execution"] = (
            "总时长为19秒的竖屏视频，保留产品特写。"
        )
        explicit_runtime_path = project / "explicit-runtime-conflict.json"
        explicit_runtime_path.write_text(
            json.dumps(explicit_runtime_conflict, ensure_ascii=False),
            encoding="utf-8",
        )
        _assert_import_rejected_without_persistence(
            project, explicit_runtime_path, "runtime_max_seconds"
        )

        explicit_cast_conflict = copy.deepcopy(candidate)
        explicit_cast_conflict["directions"][0]["story_or_behavior"] = (
            "全片共三位演员，先在便利店门口拿起真实产品，随后回到公寓客厅。"
        )
        explicit_cast_path = project / "explicit-cast-conflict.json"
        explicit_cast_path.write_text(
            json.dumps(explicit_cast_conflict, ensure_ascii=False),
            encoding="utf-8",
        )
        _assert_import_rejected_without_persistence(
            project, explicit_cast_path, "cast_max"
        )

        cases = [
            (
                "runtime_max_seconds",
                "channel_execution",
                "抖音和小红书使用25秒竖屏视频，保留产品特写。",
                "FAIL",
                {"runtime_seconds": 25},
            ),
            (
                "cast_max",
                "story_or_behavior",
                "三位演员在便利店门口拿起真实产品，随后回到公寓客厅开罐饮用。",
                "FAIL",
                {"cast_count": 3},
            ),
            (
                "location_allowlist",
                "story_or_behavior",
                "两位演员从便利店冷柜拿起真实产品，随后回到公寓客厅开罐饮用。",
                "FAIL",
                {"locations": ["便利店冷柜", "公寓客厅"]},
            ),
            (
                "product_exposure_required",
                "key_visual",
                "便利店门口的两位人物交换眼神，画面转入公寓客厅。",
                "FAIL",
                {
                    "product_exposure": {
                        "physical_product_visible": False,
                        "description": "产品不出镜，演员喝白水。",
                    }
                },
            ),
            (
                "prohibited_claims",
                "single_minded_proposition",
                "帮助睡眠，让明天更轻松。",
                "FAIL",
                {"claims": ["帮助睡眠"]},
            ),
        ]
        for kind, field, replacement, _expected, structured_updates in cases:
            broken = copy.deepcopy(candidate)
            broken["directions"][0][field] = replacement
            broken["directions"][0].update(structured_updates)
            if kind == "product_exposure_required":
                broken["directions"][0]["story_or_behavior"] = (
                    "两位演员从便利店门口走到公寓客厅，完成一次简短会面。"
                )
                broken["directions"][0]["channel_execution"] = "抖音和小红书使用18秒竖屏视频。"
            broken_path = project / f"broken-{kind}.json"
            broken_path.write_text(
                json.dumps(broken, ensure_ascii=False), encoding="utf-8"
            )
            _assert_import_rejected_without_persistence(project, broken_path, kind)

        hostile_cases = [
            (
                "unknown museum prose location",
                {"story_or_behavior": "两位演员先在公寓客厅，随后转场到美术馆。"},
                "location_allowlist",
            ),
            (
                "unknown school entrance prose location",
                {"story_or_behavior": "两位演员先在学校门口，随后回到公寓客厅。"},
                "location_allowlist",
            ),
            (
                "interior fixture relabeled as entrance",
                {"story_or_behavior": "两位演员在便利店门口打开冰柜门，取出真实产品。"},
                "location_allowlist",
            ),
            (
                "unlisted kitchen action relabeled as living room",
                {"story_or_behavior": "两位演员在公寓客厅打开冰箱取出真实产品。"},
                "location_allowlist",
            ),
            (
                "unknown bathroom prose location",
                {"story_or_behavior": "两位演员先在卫生间整理造型，随后回到公寓客厅。"},
                "location_allowlist",
            ),
            (
                "unknown warehouse prose location",
                {"story_or_behavior": "两位演员先在仓库取货，随后到便利店门口会面。"},
                "location_allowlist",
            ),
            (
                "negated product exposure",
                {
                    "story_or_behavior": "产品不出镜，演员喝白水。",
                    "product_exposure": {
                        "physical_product_visible": True,
                        "description": "产品不出镜，演员喝白水。",
                    },
                },
                "product_exposure_required",
            ),
            (
                "sleep synonym",
                {"single_minded_proposition": "一夜好眠，让明天更轻松。"},
                "prohibited_claims",
            ),
            (
                "clear headed socializing synonym",
                {"single_minded_proposition": "A clear-headed socializing choice for tonight."},
                "prohibited_claims",
            ),
            (
                "sober socializing synonym",
                {"single_minded_proposition": "Own sober socializing without compromise."},
                "prohibited_claims",
            ),
            (
                "chinese clear socializing synonym",
                {"single_minded_proposition": "把清醒社交变成今晚的新选择。"},
                "prohibited_claims",
            ),
            (
                "low burden socializing synonym",
                {"single_minded_proposition": "Low-burden socializing for modern nights."},
                "prohibited_claims",
            ),
            (
                "chinese low burden synonym",
                {"single_minded_proposition": "主打低负担社交的新生活方式。"},
                "prohibited_claims",
            ),
            (
                "wellness choice synonym",
                {"single_minded_proposition": "The wellness choice for every gathering."},
                "prohibited_claims",
            ),
            (
                "no substring inside innovation",
                {"single_minded_proposition": "Innovation sleep benefit for tomorrow."},
                "prohibited_claims",
            ),
        ]
        for label, updates, failed_kind in hostile_cases:
            broken = copy.deepcopy(candidate)
            broken["directions"][0].update(updates)
            broken_path = project / (label.replace(" ", "-") + ".json")
            broken_path.write_text(json.dumps(broken, ensure_ascii=False), encoding="utf-8")
            _assert_import_rejected_without_persistence(
                project, broken_path, failed_kind
            )

        product_language_only = copy.deepcopy(candidate)
        product_language_only["directions"][0].update(
            {
                "key_visual": "纯色字幕卡与人物眼神切换，没有实物画面。",
                "story_or_behavior": "We can open on a title card and can show a mood transition.",
                "channel_execution": "The director can hold the beat for an 18-second vertical cut.",
                "product_exposure": {
                    "physical_product_visible": True,
                    "description": "We can open softly, can show the mood, and can hold the final beat.",
                },
            }
        )
        product_language_path = project / "generic-can-verbs-are-not-product.json"
        product_language_path.write_text(
            json.dumps(product_language_only, ensure_ascii=False), encoding="utf-8"
        )
        _assert_import_rejected_without_persistence(
            project, product_language_path, "product_exposure_required"
        )

        conceptual_product = copy.deepcopy(product_language_only)
        conceptual_product["directions"][0]["story_or_behavior"] = (
            "产品策略可以展示年轻人的聚会情绪，但镜头只有人物剪影。"
        )
        conceptual_product["directions"][0]["product_exposure"]["description"] = (
            "产品概念展示在文案策略中，画面只保留人物剪影。"
        )
        conceptual_product_path = project / "product-strategy-is-not-exposure.json"
        conceptual_product_path.write_text(
            json.dumps(conceptual_product, ensure_ascii=False), encoding="utf-8"
        )
        _assert_import_rejected_without_persistence(
            project, conceptual_product_path, "product_exposure_required"
        )

        for negated_statement in (
            "本方向不出现睡眠结果，只讲产品口味。",
            "本方向没有睡眠宣称，只讲产品口味。",
            "This direction does not claim sleep benefits; it only shows taste.",
            "本方向不宣称清醒社交或低负担社交，只讲产品口味。",
            "This is not a wellness choice and does not claim sober socializing; it only shows taste.",
        ):
            negated = copy.deepcopy(candidate)
            negated["directions"][0]["single_minded_proposition"] = negated_statement
            negated_path = project / "negated-claim.json"
            negated_path.write_text(json.dumps(negated, ensure_ascii=False), encoding="utf-8")
            import_creative_candidate(project, negated_path)
            negated_review = review_creative_candidate(project)
            claim_check = negated_review.receipt["brief_constraint_checks"]["DIR-01"]
            constraint_id = next(key for key in claim_check if key.endswith(":prohibited_claims"))
            assert claim_check[constraint_id]["status"] == "PASS", (
                negated_statement,
                claim_check,
            )


def test_prohibited_claim_scan_covers_every_persisted_claim_surface() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-claim-surface-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare_hard_constraints(project)
        base = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_hard_constraint_direction(1, evidence_ref)],
        }
        unsafe = "Mori Spark makes socializing healthier for every gathering."
        for field in CLAIM_BEARING_FIELDS:
            candidate = copy.deepcopy(base)
            candidate["directions"][0][field] = unsafe
            path = project / f"unsafe-{field}.json"
            path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
            _assert_import_rejected_without_persistence(
                project, path, "prohibited_claims"
            )

        candidate = copy.deepcopy(base)
        candidate["directions"][0]["product_exposure"]["description"] += " " + unsafe
        path = project / "unsafe-product-exposure-description.json"
        path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        _assert_import_rejected_without_persistence(project, path, "prohibited_claims")

        safe_negation = "This field does not claim health benefits; it only describes taste."
        for field in CLAIM_BEARING_FIELDS:
            candidate = copy.deepcopy(base)
            candidate["directions"][0][field] = safe_negation
            path = project / f"negated-{field}.json"
            path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
            imported = import_creative_candidate(project, path)
            assert imported.current_path == project / CURRENT_GENERATION_REL
            review = review_creative_candidate(project)
            claim_checks = review.receipt["brief_constraint_checks"]["DIR-01"]
            claim_result = next(
                result
                for constraint_id, result in claim_checks.items()
                if constraint_id.endswith(":prohibited_claims")
            )
            assert claim_result["status"] == "PASS", (field, claim_result)


def test_snapshot_binds_evidence_content_and_never_reopens_after_capture() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-snapshot-content-") as raw:
        project = Path(raw)
        _prepare(project)
        evidence_path = project / EVIDENCE_REL
        records = [
            json.loads(line)
            for line in evidence_path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        records[0]["text"] += " tampered without updating sha256"
        evidence_path.write_text(
            "".join(
                json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n"
                for item in records
            ),
            encoding="utf-8",
        )
        try:
            _current_snapshot(project)
        except ValueError as exc:
            assert "evidence chunk text hash mismatch" in str(exc), str(exc)
        else:
            raise AssertionError("tampered evidence text with a stale hash must fail closed")

    with tempfile.TemporaryDirectory(prefix="adco-snapshot-one-read-") as raw:
        root = Path(raw)
        project = root / "project"
        _prepare(project)
        stored = json.loads((project / BRIEF_SNAPSHOT_REL).read_text(encoding="utf-8"))
        evidence_path = project / EVIDENCE_REL
        outside = root / "outside-evidence.jsonl"
        outside.write_text('{"chunk_id":"EVC-MAL"}\n', encoding="utf-8")
        swapped = False

        def capture_then_swap(project_arg: Path, path: Path) -> bytes | None:
            nonlocal swapped
            data = real_read_optional_project_bytes(project_arg, path)
            if Path(path) == evidence_path and not swapped:
                evidence_path.unlink()
                evidence_path.symlink_to(outside)
                swapped = True
            return data

        with patch(
            "adco_core.creative_contract.read_optional_project_bytes",
            side_effect=capture_then_swap,
        ):
            snapshot = _current_snapshot(project)
        assert swapped
        assert snapshot["brief_snapshot_sha256"] == stored["brief_snapshot_sha256"]
        assert all(item["chunk_id"] != "EVC-MAL" for item in snapshot["evidence"])


def test_local_assertion_capture_audit_and_revocation_lifecycle() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-local-assertion-lifecycle-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "local-assertion-brief.md"
        source.write_text("视频时长必须控制在20秒以内。", encoding="utf-8")
        run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-LOCAL-ASSERTION-001",
                    "file_paths": source.name,
                    "declared_semantics": "local assertion lifecycle fixture",
                }
            ],
        )
        requirements_path = project / "AD-creative/orchestrator/requirements.csv"
        with requirements_path.open(newline="", encoding="utf-8") as handle:
            requirement = next(csv.DictReader(handle))
        assertion = record_local_operator_assertion(
            project,
            semantics="creative_requirement_confirmation",
            requirement_ids=[requirement["requirement_id"]],
            note="Local operator chooses to treat the captured line as a workflow constraint.",
        )
        evidence = json.loads(assertion.evidence_path.read_text(encoding="utf-8"))
        assert evidence["identity_assurance"] == "NONE"
        assert evidence["authority_scope"] == "local_project_workflow_only"
        audit = audit_local_operator_assertions(project)
        assert len(audit) == 1 and audit[0]["status"] == "ACTIVE"
        confirm_creative_requirement(
            project,
            requirement["requirement_id"],
            confirmation_ref=assertion.assertion_ref,
        )
        revoked = revoke_local_operator_assertion(
            project,
            assertion.assertion_ref,
            reason="Fixture withdrawal",
        )
        assert revoked["source_event_id"] == assertion.assertion_ref.split(":", 1)[1]
        audit = audit_local_operator_assertions(project)
        assert len(audit) == 1 and audit[0]["status"] == "REVOKED"
        try:
            confirm_creative_requirement(
                project,
                requirement["requirement_id"],
                confirmation_ref=assertion.assertion_ref,
            )
        except ValueError as exc:
            assert "is revoked" in str(exc), str(exc)
        else:
            raise AssertionError("a revoked local assertion must not authorize workflow state")


def test_local_assertion_binding_shape_and_duplicate_ids_fail_closed() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-local-assertion-shape-") as raw:
        project = Path(raw)
        ensure_project(project)
        invalid_shapes = [
            (
                "creative_requirement_confirmation",
                ["REQ-001", "REQ-002"],
                [],
                "exactly one --requirement-id",
            ),
            (
                "creative_requirement_confirmation",
                ["REQ-001"],
                ["candidate_payload_sha256:" + "a" * 64],
                "must not include --artifact-binding",
            ),
            (
                "creative_constraint_approval",
                [],
                ["candidate_payload_sha256:" + "a" * 64],
                "exactly one --requirement-id",
            ),
            (
                "creative_constraint_rejection",
                ["REQ-001", "REQ-002"],
                ["candidate_payload_sha256:" + "a" * 64],
                "exactly one --requirement-id",
            ),
            (
                "creative_requirement_confirmation",
                ["REQ-001;REQ-002"],
                [],
                "must not contain semicolon or newline",
            ),
            (
                "creative_constraint_approval",
                ["REQ-001"],
                ["candidate_payload_sha256:" + "a" * 64],
                "needs exactly candidate_payload_sha256",
            ),
        ]
        for semantics, requirements, artifacts, expected in invalid_shapes:
            try:
                record_local_operator_assertion(
                    project,
                    semantics=semantics,
                    requirement_ids=requirements,
                    artifact_bindings=artifacts,
                    note="invalid binding-shape fixture",
                )
            except ValueError as exc:
                assert expected in str(exc), str(exc)
            else:
                raise AssertionError(f"invalid assertion shape accepted: {semantics}")

        assertion = record_local_operator_assertion(
            project,
            semantics="creative_requirement_confirmation",
            requirement_ids=["REQ-001"],
            note="duplicate source id fixture",
        )
        source_events = project / "AD-creative/orchestrator/source_events.csv"
        with source_events.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            fields = list(reader.fieldnames or [])
            rows = [dict(row) for row in reader]
        duplicate = next(
            row
            for row in rows
            if row["source_event_id"] == assertion.assertion_ref.split(":", 1)[1]
        )
        rows.append(dict(duplicate))
        with source_events.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)
        audited = audit_local_operator_assertions(project)
        assert len(audited) == 2
        assert all(item["status"] == "INVALID" for item in audited), audited
        assert all("must be non-empty and unique" in item["error"] for item in audited)


def test_local_assertion_record_and_revocation_are_concurrency_safe() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-local-assertion-concurrency-") as raw:
        project = Path(raw)
        ensure_project(project)
        original_read = creative_contract_module.read_project_text

        def slow_source_read(project_arg: Path, path: Path, **kwargs: object) -> str:
            result = original_read(project_arg, path, **kwargs)
            if Path(path) == project / creative_contract_module.SOURCE_EVENTS_REL:
                time.sleep(0.05)
            return result

        start = threading.Barrier(2)
        assertions: list[object] = []
        errors: list[BaseException] = []

        def record(requirement_id: str) -> None:
            try:
                start.wait()
                assertions.append(
                    record_local_operator_assertion(
                        project,
                        semantics="creative_requirement_confirmation",
                        requirement_ids=[requirement_id],
                        note=f"concurrent record {requirement_id}",
                    )
                )
            except BaseException as exc:  # pragma: no cover - failure reporting
                errors.append(exc)

        with patch(
            "adco_core.creative_contract.read_project_text",
            side_effect=slow_source_read,
        ):
            threads = [
                threading.Thread(target=record, args=(requirement_id,))
                for requirement_id in ("REQ-A", "REQ-B")
            ]
            for thread in threads:
                thread.start()
            for thread in threads:
                thread.join(timeout=5)
        assert not errors, errors
        assert len(assertions) == 2
        assert len(audit_local_operator_assertions(project)) == 2

        original_optional = creative_contract_module._optional_json_list
        start = threading.Barrier(2)
        errors.clear()

        def slow_revocations(project_arg: Path, rel_path: Path) -> list[dict[str, object]]:
            result = original_optional(project_arg, rel_path)
            if rel_path == creative_contract_module.LOCAL_ASSERTION_REVOCATIONS_REL:
                time.sleep(0.05)
            return result

        def revoke(assertion: object) -> None:
            try:
                start.wait()
                revoke_local_operator_assertion(
                    project,
                    assertion.assertion_ref,
                    reason="concurrent fixture revocation",
                )
            except BaseException as exc:  # pragma: no cover - failure reporting
                errors.append(exc)

        with patch(
            "adco_core.creative_contract._optional_json_list",
            side_effect=slow_revocations,
        ):
            threads = [threading.Thread(target=revoke, args=(item,)) for item in assertions]
            for thread in threads:
                thread.start()
            for thread in threads:
                thread.join(timeout=5)
        assert not errors, errors
        audited = audit_local_operator_assertions(project)
        assert len(audited) == 2
        assert all(item["status"] == "REVOKED" for item in audited), audited

        evidence_before = {
            path.name
            for path in (project / creative_contract_module.LOCAL_ASSERTIONS_REL).glob("*.json")
        }

        def fail_source_write(project_arg: Path, path: Path, data: bytes) -> Path:
            if Path(path) == project / creative_contract_module.SOURCE_EVENTS_REL:
                raise OSError("fixture source-event commit failure")
            return real_atomic_write_bytes(project_arg, path, data)

        with patch(
            "adco_core.creative_contract.atomic_write_bytes",
            side_effect=fail_source_write,
        ):
            try:
                record_local_operator_assertion(
                    project,
                    semantics="creative_requirement_confirmation",
                    requirement_ids=["REQ-ORPHAN"],
                    note="must roll back orphan evidence",
                )
            except OSError as exc:
                assert "source-event commit failure" in str(exc), str(exc)
            else:
                raise AssertionError("source-event write failure must be reported")
        evidence_after = {
            path.name
            for path in (project / creative_contract_module.LOCAL_ASSERTIONS_REL).glob("*.json")
        }
        assert evidence_after == evidence_before

        with project_advisory_lock(project, "local-operator-assertions"):
            with project_advisory_lock(project.resolve(), "local-operator-assertions"):
                pass

        active = 0
        max_active = 0
        active_guard = threading.Lock()
        alias_start = threading.Barrier(2)

        def alias_lock(path: Path) -> None:
            nonlocal active, max_active
            alias_start.wait()
            with project_advisory_lock(path, "alias-fixture"):
                with active_guard:
                    active += 1
                    max_active = max(max_active, active)
                time.sleep(0.05)
                with active_guard:
                    active -= 1

        aliases = [project, project.resolve()]
        alias_threads = [threading.Thread(target=alias_lock, args=(path,)) for path in aliases]
        for thread in alias_threads:
            thread.start()
        for thread in alias_threads:
            thread.join(timeout=5)
            assert not thread.is_alive()
        assert max_active == 1

        replacement_root = Path(raw) / "replacement-project"
        replacement_root.mkdir()
        first_entered = threading.Event()
        release_first = threading.Event()
        second_entered = threading.Event()

        def hold_original_root() -> None:
            with project_advisory_lock(replacement_root, "root-replacement-fixture"):
                first_entered.set()
                assert release_first.wait(timeout=5)

        first_thread = threading.Thread(target=hold_original_root)
        first_thread.start()
        assert first_entered.wait(timeout=5)
        parked_root = Path(raw) / "replacement-project-parked"
        replacement_root.rename(parked_root)
        replacement_root.mkdir()

        def enter_replacement_root() -> None:
            with project_advisory_lock(replacement_root, "root-replacement-fixture"):
                second_entered.set()

        second_thread = threading.Thread(target=enter_replacement_root)
        second_thread.start()
        assert not second_entered.wait(timeout=0.15)
        release_first.set()
        assert second_entered.wait(timeout=5)
        first_thread.join(timeout=5)
        second_thread.join(timeout=5)
        assert not first_thread.is_alive() and not second_thread.is_alive()

        nested_root = Path(raw) / "nested-root-replacement"
        nested_root.mkdir()
        nested_parked = Path(raw) / "nested-root-replacement-parked"
        nested_entered = False
        with project_advisory_lock(nested_root, "nested-root-replacement-fixture"):
            nested_root.rename(nested_parked)
            nested_root.mkdir()
            try:
                with project_advisory_lock(
                    nested_root, "nested-root-replacement-fixture"
                ):
                    nested_entered = True
            except ValueError as exc:
                assert "root identity changed" in str(exc), str(exc)
            else:
                raise AssertionError("nested replacement root must fail closed")
        assert nested_entered is False

        process_marker = Path(raw) / "process-lock-entered"
        process_script = """
import sys
import time
from pathlib import Path
from adco_core.safe_write import project_advisory_lock
with project_advisory_lock(Path(sys.argv[1]), 'process-fixture'):
    Path(sys.argv[2]).write_text('entered', encoding='utf-8')
    time.sleep(0.5)
"""
        process_env = os.environ.copy()
        tools_root = str(Path(__file__).resolve().parent)
        process_env["PYTHONPATH"] = (
            tools_root
            + (os.pathsep + process_env["PYTHONPATH"] if process_env.get("PYTHONPATH") else "")
        )
        process = subprocess.Popen(
            [sys.executable, "-c", process_script, str(project), str(process_marker)],
            env=process_env,
        )
        deadline = time.monotonic() + 5
        while not process_marker.exists() and time.monotonic() < deadline:
            time.sleep(0.01)
        assert process_marker.exists()
        started = time.monotonic()
        with project_advisory_lock(project, "process-fixture"):
            elapsed = time.monotonic() - started
        assert elapsed >= 0.25, elapsed
        assert process.wait(timeout=5) == 0


def test_unconfirmed_and_unsupported_hard_requirements_block_before_write() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-unconfirmed-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare_hard_constraints(
            project, confirm=False
        )
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        assert contract["hard_constraints"]
        assert all(
            item["workflow_assertion"]["enforceable_in_local_workflow"] is False
            for item in contract["hard_constraints"]
        )
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_hard_constraint_direction(1, evidence_ref)],
        }
        candidate_path = project / "unconfirmed.json"
        candidate_path.write_text(
            json.dumps(candidate, ensure_ascii=False), encoding="utf-8"
        )
        _assert_import_rejected_without_persistence(
            project, candidate_path, "lacks an active local workflow assertion"
        )

    with tempfile.TemporaryDirectory(prefix="adco-creative-manual-hard-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "manual-hard.md"
        source.write_text(
            "必须一天拍完。\n禁止任何虚构数据。",
            encoding="utf-8",
        )
        intake = run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-MANUAL-001",
                    "file_paths": source.name,
                    "declared_semantics": "manual hard constraint fixture",
                }
            ],
        )
        _confirm_requirements(project)
        brief = create_creative_brief(project)
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        assert {item["kind"] for item in contract["hard_constraints"]} == {
            "manual_review"
        }
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": brief.snapshot_sha256,
            "directions": [_direction(1, intake.ingestion.chunks[0].chunk_id)],
        }
        candidate_path = project / "manual-review-required.json"
        candidate_path.write_text(
            json.dumps(candidate, ensure_ascii=False), encoding="utf-8"
        )
        _assert_import_rejected_without_persistence(
            project, candidate_path, "no deterministic checker"
        )


def test_product_exposure_negation_is_not_reversed() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-no-product-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "no-product.md"
        source.write_text("必须避免产品露出。", encoding="utf-8")
        intake = run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-NO-PRODUCT-001",
                    "file_paths": source.name,
                    "declared_semantics": "product exposure prohibition fixture",
                }
            ],
        )
        _confirm_requirements(project)
        brief = create_creative_brief(project)
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        constraint = next(
            item
            for item in contract["hard_constraints"]
            if item["kind"] == "product_exposure_required"
        )
        assert constraint["value"] is False

        direction = _direction(1, intake.ingestion.chunks[0].chunk_id)
        direction["key_visual"] = "雨滴沿玻璃流动，人物影子在背景中缓慢经过。"
        direction["story_or_behavior"] = "人物只通过环境和动作表达选择，镜头保持克制。"
        direction["channel_execution"] = "15秒竖屏氛围短片。"
        direction["product_exposure"] = {
            "physical_product_visible": False,
            "description": "画面仅包含环境与人物动作。",
        }
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": brief.snapshot_sha256,
            "directions": [direction],
        }
        candidate_path = project / "no-product-candidate.json"
        candidate_path.write_text(
            json.dumps(candidate, ensure_ascii=False), encoding="utf-8"
        )
        import_creative_candidate(project, candidate_path)
        review = review_creative_candidate(project)
        assert review.receipt["brief_adherence"]["DIR-01"]["status"] == "PASS"

        violating = copy.deepcopy(candidate)
        violating["directions"][0]["product_exposure"] = {
            "physical_product_visible": True,
            "description": "真实产品包装出镜并展示。",
        }
        violating_path = project / "product-visible.json"
        violating_path.write_text(
            json.dumps(violating, ensure_ascii=False), encoding="utf-8"
        )
        _assert_import_rejected_without_persistence(
            project, violating_path, "product_exposure_required"
        )


def test_direction_count_matches_request_without_forced_critic() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-count-") as raw:
        project = Path(raw)
        ensure_delivery_project(project)
        source = project / "one-direction-brief.md"
        source.write_text("本轮只要1个创意方向，不需要独立 Critic。", encoding="utf-8")
        intake = run_evidence_intake(
            project,
            [{"source_event_id": "SRC-COUNT-001", "file_paths": source.name, "declared_semantics": "count fixture"}],
        )
        brief = create_creative_brief(project)
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        schema = json.loads((project / CANDIDATE_SCHEMA_REL).read_text(encoding="utf-8"))
        assert contract["candidate_contract"]["requested_direction_count"] == 1
        assert contract["candidate_contract"]["critic_required_by_brief"] is False
        assert schema["properties"]["directions"]["minItems"] == 1
        assert schema["properties"]["directions"]["maxItems"] == 1
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": brief.snapshot_sha256,
            "directions": [_direction(1, intake.ingestion.chunks[0].chunk_id)],
        }
        candidate_path = project / "one-direction.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        proposal_structure = (
            project / "AD-creative/proposal_architecture/proposal_structure.md"
        )
        adversarial_path = (
            project / "AD-creative/gates/ADVERSARIAL_REVIEW_CREATIVE.md"
        )
        write_text(
            adversarial_path,
            f"""# Independent Adversarial Review

stage: creative
reviewer_id: fixture-independent-reviewer
reviewer_role: cold reviewer
independent: true
reviewed_at: {now_iso()}
target_ref: {proposal_structure.relative_to(project).as_posix()}
target_sha256: {file_sha256(proposal_structure)}

| stage | objection | rebuttal | revision | gate_status |
|---|---|---|---|---|
| creative | Pre-import static target | Static review only | Review current generation | PASS |
""",
        )
        imported = import_creative_candidate(project, candidate_path)
        assert imported.direction_count == 1
        generation_paths = current_creative_generation_paths(project)
        current_directions = generation_paths["directions"]
        legacy_directions = project / "AD-creative/creative/creative_directions.md"
        targets = default_adversarial_targets(project, "creative")
        assert current_directions in targets
        assert legacy_directions not in targets

        found, evidence = adversarial_council_evidence(project, "creative")
        assert found is False and evidence == []

        def write_adversarial_review(target: Path) -> None:
            write_text(
                adversarial_path,
                f"""# Independent Adversarial Review

stage: creative
reviewer_id: fixture-independent-reviewer
reviewer_role: cold reviewer
independent: true
reviewed_at: {now_iso()}
target_ref: {target.relative_to(project).as_posix()}
target_sha256: {file_sha256(target)}

| stage | objection | rebuttal | revision | gate_status |
|---|---|---|---|---|
| creative | Challenge stale target use | Bound current review | Retain verified route | PASS |
""",
            )

        write_adversarial_review(legacy_directions)
        found, evidence = adversarial_council_evidence(project, "creative")
        assert found is False and evidence == []
        write_adversarial_review(current_directions)
        found, evidence = adversarial_council_evidence(project, "creative")
        assert found is True and evidence

        review = review_creative_candidate(project)
        assert review.receipt_path is None
        assert review.receipt["independent_critic_required"] is False
        deterministic_receipt = project / DETERMINISTIC_LINT_RECEIPT_REL
        assert not deterministic_receipt.exists()
        quality_status, quality_findings, _ = review_creative_quality(project)
        assert quality_status != "BLOCKED", (quality_status, quality_findings)
        assert deterministic_receipt.exists()
        deterministic_payload = json.loads(
            deterministic_receipt.read_text(encoding="utf-8")
        )
        assert deterministic_payload["independent_critic_required"] is False
        output = io.StringIO()
        with redirect_stdout(output):
            exit_code = command_creative_review(
                argparse.Namespace(project=str(project), json=True)
            )
        cli_payload = json.loads(output.getvalue())
        assert exit_code == 0
        assert cli_payload["independent_critic_required"] is False
        assert "REQUIRES_INDEPENDENT_CRITIC" not in cli_payload["verdict"]
        assert not any(
            "creative_deterministic_lint_receipt.json" in item
            or "少于 2 条" in item
            or "独立创意 Critic" in item
            for item in quality_findings
        ), quality_findings
        film_status, film_findings, film_report = review_film_quality(project)
        assert film_status in {"BLOCKED", "PARTIAL_PASS", "PASS"}, film_findings
        film_report_text = film_report.read_text(encoding="utf-8")
        assert (
            f"creative_directions={current_directions.relative_to(project).as_posix()}"
            in film_report_text
        )

        thread_plan = render_thread_execution_plan(
            project,
            goal_id="GOAL-CURRENT-CREATIVE",
            title="Current creative review",
            objective="Review the exact current creative generation.",
            roles=["copy_creative"],
        )
        prompt_text = thread_plan["prompts"][0].read_text(encoding="utf-8")
        current_rel = current_directions.relative_to(project).as_posix()
        assert current_rel in prompt_text
        assert "AD-creative/creative/creative_directions.md" not in prompt_text

        with patch(
            "ad_creative_operator.creative_brief_requires_independent_critic",
            side_effect=ValueError("fixture corrupt brief contract"),
        ):
            corrupt_status, corrupt_findings, _ = review_creative_quality(project)
        assert corrupt_status == "BLOCKED"
        assert any("fixture corrupt brief contract" in item for item in corrupt_findings)

        (project / CURRENT_GENERATION_REL).unlink()
        for current_consumer in (
            lambda: current_creative_generation_paths(project),
            lambda: creative_proposal_scan_files(project),
            lambda: default_adversarial_targets(project, "creative"),
        ):
            try:
                current_consumer()
            except ValueError as exc:
                assert "pointer is missing" in str(exc), str(exc)
            else:
                raise AssertionError(
                    "current-generation consumers must fail closed when the pointer is deleted"
                )


def test_common_english_prohibited_claim_phrase_is_extracted() -> None:
    assert _prohibited_claims(
        "Must not make sleep, sobering, weight-loss, health, or medical claims."
    ) == ["sleep", "sobering", "weight-loss", "health", "medical"]


def test_candidate_generation_never_reuses_tampered_bytes() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-version-binding-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref), _direction(2, evidence_ref)],
        }
        candidate_path = project / "candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        first = import_creative_candidate(project, candidate_path)
        first_payload_digest = payload_sha256(candidate)
        first.candidate_path.write_text(
            json.dumps(candidate, ensure_ascii=False, indent=4) + "\n\n",
            encoding="utf-8",
        )
        assert json.loads(first.candidate_path.read_text(encoding="utf-8")) == candidate
        assert payload_sha256(
            json.loads(first.candidate_path.read_text(encoding="utf-8"))
        ) == first_payload_digest
        second = import_creative_candidate(project, candidate_path)
        assert second.candidate_path != first.candidate_path
        assert second.candidate_path.name == "candidate.json"
        assert second.candidate_path.parent != first.candidate_path.parent
        persisted = json.loads(second.candidate_path.read_text(encoding="utf-8"))
        assert persisted == candidate
        receipt = json.loads(second.receipt_path.read_text(encoding="utf-8"))
        assert receipt["candidate_path"] == second.candidate_path.relative_to(project).as_posix()
        assert receipt["candidate_sha256"] == second.candidate_sha256
        assert receipt["candidate_sha256"] == file_sha256(second.candidate_path)
        assert receipt["candidate_payload_sha256"] == first_payload_digest
        assert receipt["candidate_byte_length"] == len(second.candidate_path.read_bytes())


def test_brief_manifest_self_hash_and_current_truth_are_fail_closed() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-brief-integrity-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref)],
        }
        candidate_path = project / "candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")

        snapshot_path = project / BRIEF_SNAPSHOT_REL
        manifest_path = project / BRIEF_MANIFEST_REL
        snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
        snapshot["brief_snapshot_sha256"] = "0" * 64
        snapshot_bytes = (
            json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        ).encode("utf-8")
        snapshot_path.write_bytes(snapshot_bytes)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["brief_snapshot_sha256"] = "0" * 64
        manifest["artifacts"][BRIEF_SNAPSHOT_REL.as_posix()] = {
            "sha256": __import__("hashlib").sha256(snapshot_bytes).hexdigest(),
            "byte_length": len(snapshot_bytes),
        }
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        _assert_import_rejected_without_persistence(
            project,
            candidate_path,
            "snapshot self-hash mismatch",
        )

    with tempfile.TemporaryDirectory(prefix="adco-creative-brief-stale-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref)],
        }
        candidate_path = project / "candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        requirements_path = project / "AD-creative/orchestrator/requirements.csv"
        requirements_path.write_text(
            requirements_path.read_text(encoding="utf-8").replace(
                "可编辑广告提案", "可编辑广告提案并补一张KV"
            ),
            encoding="utf-8",
        )
        _assert_import_rejected_without_persistence(
            project,
            candidate_path,
            "creative brief is stale against current",
        )


def test_review_requires_exact_current_version_and_import_receipt_chain() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-review-binding-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref), _direction(2, evidence_ref)],
        }
        candidate_path = project / "candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        imported = import_creative_candidate(project, candidate_path)
        assert review_creative_candidate(project).status == "PARTIAL_PASS"

        receipt_path = imported.receipt_path
        receipt_bytes = receipt_path.read_bytes()
        receipt = json.loads(receipt_bytes)
        receipt["candidate_sha256"] = "f" * 64
        receipt_path.write_text(json.dumps(receipt, ensure_ascii=False), encoding="utf-8")
        try:
            review_creative_candidate(project)
        except ValueError as exc:
            assert "generation receipt hash does not match manifest" in str(exc), str(exc)
        else:
            raise AssertionError("review must reject a tampered import receipt")
        receipt_path.write_bytes(receipt_bytes)

        version_bytes = imported.candidate_path.read_bytes()
        imported.candidate_path.write_text(
            json.dumps(candidate, ensure_ascii=False, indent=4) + "\n",
            encoding="utf-8",
        )
        try:
            review_creative_candidate(project)
        except ValueError as exc:
            assert "generation candidate hash does not match manifest" in str(exc)
        else:
            raise AssertionError("review must reject semantically equal but byte-different version")
        imported.candidate_path.write_bytes(version_bytes)
        assert review_creative_candidate(project).status == "PARTIAL_PASS"


def test_local_requirement_assertion_and_manual_constraint_resolution() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-human-resolution-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "manual-hard.md"
        source.write_text("必须一天拍完。", encoding="utf-8")
        intake = run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-MANUAL-RESOLVE-001",
                    "file_paths": source.name,
                    "declared_semantics": "manual constraint resolution fixture",
                }
            ],
        )

        # A hand-edited status has no matching receipt and remains non-authoritative.
        requirements_path = project / "AD-creative/orchestrator/requirements.csv"
        with requirements_path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            fields = list(reader.fieldnames or [])
            rows = [dict(row) for row in reader]
        rows[0]["status"] = "confirmed"
        rows[0]["confirmed_by"] = "Fixture Human Reviewer"
        rows[0]["confirmed_at"] = "2026-07-22T00:00:00+08:00"
        with requirements_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)
        untrusted_brief = create_creative_brief(project)
        untrusted_contract = json.loads(
            (project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8")
        )
        assert (
            untrusted_contract["hard_constraints"][0]["workflow_assertion"]
            ["enforceable_in_local_workflow"]
            is False
        )

        try:
            confirm_creative_requirement(
                project,
                rows[0]["requirement_id"],
                confirmation_ref="Fixture Human Reviewer",
            )
        except ValueError as exc:
            assert "confirmation_ref must be" in str(exc)
        else:
            raise AssertionError("a free-text reviewer name must never confer authority")

        requirement_confirmation_ref = _append_confirmation_event(
            project,
            event_id="CONFIRM-MANUAL-REQ-001",
            semantics="creative_requirement_confirmation",
            affects_requirements={rows[0]["requirement_id"]},
        )
        confirmation = confirm_creative_requirement(
            project,
            rows[0]["requirement_id"],
            confirmation_ref=requirement_confirmation_ref,
        )
        assert confirmation.receipt["evidence_ref"] == intake.ingestion.chunks[0].chunk_id
        brief = create_creative_brief(project)
        assert brief.snapshot_sha256 != untrusted_brief.snapshot_sha256
        contract = json.loads((project / BRIEF_CONTRACT_REL).read_text(encoding="utf-8"))
        constraint = contract["hard_constraints"][0]
        assert constraint["kind"] == "manual_review"
        assert (
            constraint["workflow_assertion"]["enforceable_in_local_workflow"]
            is True
        )

        candidate = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": brief.snapshot_sha256,
            "directions": [_direction(1, intake.ingestion.chunks[0].chunk_id)],
        }
        candidate_path = project / "manual-candidate.json"
        candidate_path.write_text(json.dumps(candidate, ensure_ascii=False), encoding="utf-8")
        _assert_import_rejected_without_persistence(
            project,
            candidate_path,
            "no deterministic checker",
        )
        constraint_confirmation_ref = _append_confirmation_event(
            project,
            event_id="CONFIRM-MANUAL-CONSTRAINT-001",
            semantics="creative_constraint_approval",
            affects_requirements={constraint["requirement_id"]},
            affects_artifacts={
                f"candidate_payload_sha256:{payload_sha256(candidate)}",
                f"brief_snapshot_sha256:{candidate['brief_snapshot_sha256']}",
                "direction_id:DIR-01",
                f"constraint_id:{constraint['constraint_id']}",
            },
        )
        with (
            project / "AD-creative/orchestrator/source_events.csv"
        ).open(newline="", encoding="utf-8") as handle:
            constraint_event_id = constraint_confirmation_ref.split(":", 1)[1]
            control_event = next(
                row
                for row in csv.DictReader(handle)
                if row["source_event_id"] == constraint_event_id
            )
        control_intake = _run_evidence_intake_impl(project, [control_event])
        assert control_intake.ingestion.chunks == []
        resolution = resolve_creative_constraint(
            project,
            candidate_path,
            direction_id="DIR-01",
            constraint_id=constraint["constraint_id"],
            confirmation_ref=constraint_confirmation_ref,
            decision="approved",
            note="Production plan and call sheet were reviewed; the direction fits one shoot day.",
        )
        assert resolution.resolution["decision"] == "approved"
        import_creative_candidate(project, candidate_path)
        assert review_creative_candidate(project).receipt["brief_adherence"]["DIR-01"]["status"] == "PASS"

        changed = copy.deepcopy(candidate)
        changed["directions"][0]["production_risk"] += " 已变更。"
        changed_path = project / "changed-manual-candidate.json"
        changed_path.write_text(json.dumps(changed, ensure_ascii=False), encoding="utf-8")
        _assert_import_rejected_without_persistence(
            project,
            changed_path,
            "no deterministic checker",
        )

        constraint_evidence = project / control_event["file_paths"]
        constraint_evidence.write_text("tampered confirmation\n", encoding="utf-8")
        stale_review = review_creative_candidate(project)
        assert stale_review.blocking_issues
        assert (
            stale_review.receipt["brief_adherence"]["DIR-01"]["status"]
            == "REVIEW_REQUIRED"
        )


def test_local_assertion_rejects_forged_identity_and_binding() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-confirmation-authority-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "authority-brief.md"
        source.write_text("视频时长必须控制在20秒以内。", encoding="utf-8")
        run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-AUTHORITY-001",
                    "file_paths": source.name,
                    "declared_semantics": "authority fixture",
                }
            ],
        )
        requirements_path = project / "AD-creative/orchestrator/requirements.csv"
        with requirements_path.open(newline="", encoding="utf-8") as handle:
            requirement = next(csv.DictReader(handle))
        confirmation_ref = _append_confirmation_event(
            project,
            event_id="CONFIRM-AUTHORITY-001",
            semantics="creative_requirement_confirmation",
            affects_requirements={requirement["requirement_id"]},
        )
        source_events_path = project / "AD-creative/orchestrator/source_events.csv"
        with source_events_path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            fields = list(reader.fieldnames or [])
            rows = [dict(row) for row in reader]
        confirmation_event_id = confirmation_ref.split(":", 1)[1]
        confirmation_row = next(
            row for row in rows if row["source_event_id"] == confirmation_event_id
        )

        for field, forged_value, expected_error in (
            (
                "source_owner",
                "Fixture Human Reviewer",
                "source_owner must be local_operator",
            ),
            (
                "source_type",
                "user_confirmation",
                "source_type must be local_operator_assertion",
            ),
            (
                "trust_level",
                "user_confirmed",
                "trust_level must be local_asserted",
            ),
            ("affects_requirements", "REQ-NOT-TARGET", "must exactly bind"),
        ):
            original = confirmation_row[field]
            confirmation_row[field] = forged_value
            with source_events_path.open("w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(handle, fieldnames=fields)
                writer.writeheader()
                writer.writerows(rows)
            try:
                confirm_creative_requirement(
                    project,
                    requirement["requirement_id"],
                    confirmation_ref=confirmation_ref,
                )
            except ValueError as exc:
                assert expected_error in str(exc), str(exc)
            else:
                raise AssertionError(f"forged confirmation field must fail: {field}")
            confirmation_row[field] = original


def test_anchored_project_io_resists_symlink_swap_races() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-safe-write-race-") as raw:
        root = Path(raw)
        project = root / "project"
        target_parent = project / "AD-creative/race"
        outside = root / "outside"
        target_parent.mkdir(parents=True)
        outside.mkdir()
        target = target_parent / "truth.json"
        secret = outside / "secret.json"
        target.write_bytes(b"SAFE")
        target.chmod(0o644)
        secret.write_bytes(b"EXTERNAL_SECRET")
        stop = threading.Event()
        attacker_errors: list[BaseException] = []

        def swap_target() -> None:
            try:
                while not stop.is_set():
                    try:
                        target.unlink()
                    except FileNotFoundError:
                        pass
                    try:
                        os.symlink(secret, target)
                    except FileExistsError:
                        pass
                    try:
                        target.unlink()
                    except FileNotFoundError:
                        pass
                    try:
                        descriptor = os.open(
                            target,
                            os.O_WRONLY
                            | os.O_CREAT
                            | os.O_EXCL
                            | getattr(os, "O_NOFOLLOW", 0),
                            0o644,
                        )
                    except FileExistsError:
                        continue
                    try:
                        os.write(descriptor, b"SAFE")
                    finally:
                        os.close(descriptor)
            except BaseException as exc:  # pragma: no cover - surfaced below
                attacker_errors.append(exc)

        attacker = threading.Thread(target=swap_target, daemon=True)
        attacker.start()
        try:
            for index in range(800):
                try:
                    observed = read_project_bytes(project, target)
                except (OSError, ValueError):
                    pass
                else:
                    assert observed != b"EXTERNAL_SECRET"
                try:
                    atomic_write_text(project, target, f"SAFE-{index}")
                except (OSError, ValueError):
                    pass
        finally:
            stop.set()
            attacker.join(timeout=5)
        assert not attacker.is_alive()
        assert not attacker_errors, attacker_errors
        assert secret.read_bytes() == b"EXTERNAL_SECRET"

        if target.is_symlink():
            target.unlink()
        atomic_write_text(project, target, "mode-preserved")
        target.chmod(0o644)
        atomic_write_text(project, target, "mode-still-preserved")
        assert target.stat().st_mode & 0o777 == 0o644


def test_anchored_project_read_resists_parent_directory_swap() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-safe-parent-race-") as raw:
        root = Path(raw)
        project = root / "project"
        stable_parent = project / "AD-creative/parent-race"
        parked_parent = project / "AD-creative/parent-race-parked"
        outside_parent = root / "outside-parent"
        stable_parent.mkdir(parents=True)
        outside_parent.mkdir()
        (stable_parent / "truth.txt").write_bytes(b"SAFE_PARENT")
        (outside_parent / "truth.txt").write_bytes(b"EXTERNAL_SECRET")
        stop = threading.Event()
        attacker_errors: list[BaseException] = []

        def swap_parent() -> None:
            try:
                while not stop.is_set():
                    try:
                        os.rename(stable_parent, parked_parent)
                    except OSError:
                        continue
                    try:
                        os.symlink(outside_parent, stable_parent)
                        stable_parent.unlink()
                    finally:
                        try:
                            os.rename(parked_parent, stable_parent)
                        except OSError:
                            pass
            except BaseException as exc:  # pragma: no cover - surfaced below
                attacker_errors.append(exc)

        attacker = threading.Thread(target=swap_parent, daemon=True)
        attacker.start()
        try:
            for _ in range(1600):
                try:
                    observed = read_project_bytes(
                        project, stable_parent / "truth.txt"
                    )
                except (OSError, ValueError):
                    continue
                assert observed == b"SAFE_PARENT"
        finally:
            stop.set()
            attacker.join(timeout=5)
        assert not attacker.is_alive()
        assert not attacker_errors, attacker_errors
        assert (outside_parent / "truth.txt").read_bytes() == b"EXTERNAL_SECRET"


def test_conflicting_direction_counts_and_atomic_pointer_switch_fail_closed() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-count-conflict-") as raw:
        project = Path(raw)
        ensure_project(project)
        source = project / "count-conflict.md"
        source.write_text(
            "本轮只要1个创意方向。\n同时要求提供2个创意方向。",
            encoding="utf-8",
        )
        run_evidence_intake(
            project,
            [
                {
                    "source_event_id": "SRC-COUNT-CONFLICT-001",
                    "file_paths": source.name,
                    "declared_semantics": "conflicting direction count fixture",
                }
            ],
        )
        try:
            create_creative_brief(project)
        except ValueError as exc:
            assert "conflicting explicit creative direction counts" in str(exc)
        else:
            raise AssertionError("conflicting explicit direction counts must fail closed")
        assert not (project / BRIEF_MANIFEST_REL).exists()

    with tempfile.TemporaryDirectory(prefix="adco-creative-atomic-current-") as raw:
        project = Path(raw)
        snapshot_sha, evidence_ref = _prepare(project)
        first = {
            "candidate_version": "1.1",
            "brief_snapshot_sha256": snapshot_sha,
            "directions": [_direction(1, evidence_ref), _direction(2, evidence_ref)],
        }
        first_path = project / "first.json"
        first_path.write_text(json.dumps(first, ensure_ascii=False), encoding="utf-8")
        import_creative_candidate(project, first_path)
        current_path = project / CURRENT_GENERATION_REL
        old_current = current_path.read_bytes()
        old_paths = current_creative_generation_paths(project)
        old_visible = {
            role: old_paths[role].read_bytes()
            for role in ("candidate", "receipt", "directions", "matrix")
        }

        second = copy.deepcopy(first)
        second["directions"][0]["name"] = "雨线显形升级"
        second["directions"][0]["creative_mechanism"] = "雨滴路径分层显形"
        second_path = project / "second.json"
        second_path.write_text(json.dumps(second, ensure_ascii=False), encoding="utf-8")

        def fail_current(project_arg: Path, path: Path, data: bytes) -> Path:
            if Path(path) == current_path:
                raise OSError("injected current pointer failure")
            return real_atomic_write_bytes(project_arg, path, data)

        with patch("adco_core.creative_contract.atomic_write_bytes", side_effect=fail_current):
            try:
                import_creative_candidate(project, second_path)
            except OSError as exc:
                assert "injected current pointer failure" in str(exc)
            else:
                raise AssertionError("fault injection must interrupt current pointer switch")
        assert current_path.read_bytes() == old_current
        current_paths = current_creative_generation_paths(project)
        assert {
            role: current_paths[role].read_bytes()
            for role in ("candidate", "receipt", "directions", "matrix")
        } == old_visible
        scanned = {path.resolve() for path in creative_proposal_scan_files(project)}
        assert old_paths["candidate"].resolve() in scanned
        assert old_paths["directions"].resolve() in scanned
        assert old_paths["matrix"].resolve() in scanned
        assert review_creative_candidate(project).status == "PARTIAL_PASS"
        import_creative_candidate(project, second_path)
        assert review_creative_candidate(project).status == "PARTIAL_PASS"


def test_project_artifact_writer_rejects_nested_symlink() -> None:
    with tempfile.TemporaryDirectory(prefix="adco-creative-symlink-") as raw:
        project = Path(raw) / "project"
        outside = Path(raw) / "outside"
        ensure_project(project)
        outside.mkdir()
        linked = project / "AD-creative/linked-outside"
        linked.symlink_to(outside, target_is_directory=True)
        try:
            atomic_write_text(project, linked / "escaped.json", "do not write")
        except ValueError as exc:
            assert "must not be a symlink" in str(exc)
        else:
            raise AssertionError("nested symlink writes must be rejected")
        assert not (outside / "escaped.json").exists()


def main() -> int:
    test_brief_generates_contracts_not_directions()
    test_candidate_requires_evidence_and_distinct_mechanisms()
    test_hard_constraints_are_semantically_checked_and_fail_closed()
    test_prohibited_claim_scan_covers_every_persisted_claim_surface()
    test_snapshot_binds_evidence_content_and_never_reopens_after_capture()
    test_local_assertion_capture_audit_and_revocation_lifecycle()
    test_local_assertion_binding_shape_and_duplicate_ids_fail_closed()
    test_local_assertion_record_and_revocation_are_concurrency_safe()
    test_unconfirmed_and_unsupported_hard_requirements_block_before_write()
    test_product_exposure_negation_is_not_reversed()
    test_direction_count_matches_request_without_forced_critic()
    test_common_english_prohibited_claim_phrase_is_extracted()
    test_candidate_generation_never_reuses_tampered_bytes()
    test_brief_manifest_self_hash_and_current_truth_are_fail_closed()
    test_review_requires_exact_current_version_and_import_receipt_chain()
    test_local_requirement_assertion_and_manual_constraint_resolution()
    test_local_assertion_rejects_forged_identity_and_binding()
    test_conflicting_direction_counts_and_atomic_pointer_switch_fail_closed()
    test_project_artifact_writer_rejects_nested_symlink()
    test_anchored_project_io_resists_symlink_swap_races()
    test_anchored_project_read_resists_parent_directory_swap()
    print("TEST_CREATIVE_CONTRACT=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
